arxanas/git-branchless

.github/workflows/ci.yml
src/commands/wrap.rs
src/testing.rs
src/util.rs
tests/core/test_hooks.rs

This PR fixes various issues affecting execution of git-branchless commands and tests on Windows.
- Fixes handling of PATH environment variable (separator)
- Calls "echo" from PATH on Windows, as git-bash actually keeps it at /usr/bin/echo
- Strips EL VT sequence from test output (injected by git.exe or ConPTY?)
- Use ":" for GIT_EDITOR to have git skip commit editing (during test invocations)
- Provide a default git.exe path (for when use_system_git == true)
- Call hooks via execution of sh, using git-bash on Windows when found.
With these changes all tests pass and commands appear to work as intended.

Fix tests and execution on Windows

---

.github/workflows/fmt.yml
.github/workflows/lint.yml
.github/workflows/linux.yml
.github/workflows/macos.yml
.github/workflows/windows.yml
README.md

Allows the reader to see that the project's CI supports their platform
at a glance.
Badge links format looks to have changed. Tested by pointing temporarily
at my own repo to see the badges in the rendered README.md.

Split CI workflows up for the OS badges

---

CHANGELOG.md
src/commands/wrap.rs
tests/command/test_wrap.rs
tests/mod.rs

- refactor(wrap): move test cases out of source module
- fix(wrap): don't fail if no Git repository is available

Fix `git wrap` when there is no repository

---

CHANGELOG.md

Since `git branchless wrap` was released in v0.3.2, it doesn't make sense to also include items in the changelog about how the feature has changed.

docs(wrap): remove item about adding a feature to `git branchless wrap`

---

.github/workflows/lint.yml
.github/workflows/linux.yml
.github/workflows/macos.yml
.github/workflows/windows.yml

Since this is my repository, I typically use its branches to open pull requests. But that means that each job gets run twice as a result. Instead, I'll just use the pull request workflow if I want to manually trigger a build.

ci: only trigger CI runs when pushing to `master` branch

---

src/util.rs

Following is happening:
'''
error: cannot spawn .git/hooks/post-rewrite: No such file or directory: No such file or directory
'''
because the first line of the stubbed post-rewrite is a new-line, which
is interpretted by mingw as "not a shell script".

Fix 'cannot spawn .git/hooks/post-rewrite' on Windows

---

CHANGELOG.md
Cargo.lock
Cargo.toml
src/commands/init.rs
src/commands/move.rs
src/commands/navigation.rs
src/commands/restack.rs
src/commands/undo.rs
src/commands/wrap.rs
src/core/rewrite.rs
src/main.rs
src/testing.rs
src/util.rs
tests/command/test_smartlog.rs
tests/command/test_undo.rs
tests/core/test_hooks.rs

- refactor(util): rename `GitExecutable` to `GitRunInfo`
- refactor(util): store more environment information in `GitRunInfo`

Attempt to fix flaky undo tests (closes #23)

---

src/commands/hooks.rs
src/commands/wrap.rs
src/core/eventlog.rs
src/core/graph.rs
src/core/rewrite.rs
src/testing.rs
src/util.rs
tests/command/test_hide.rs
tests/command/test_init.rs
tests/command/test_move.rs
tests/command/test_navigation.rs
tests/command/test_restack.rs
tests/command/test_smartlog.rs
tests/command/test_undo.rs
tests/command/test_wrap.rs
tests/core/test_eventlog.rs
tests/core/test_gc.rs
tests/core/test_hooks.rs
tests/test_branchless.rs

Using `Drop` is probably more idiomatic Rust than wrapping the function body in a lambda.

refactor(tests): `with_git` -> `make_git`

---

CHANGELOG.md
src/commands/gc.rs
src/commands/hooks.rs
src/commands/move.rs
src/commands/navigation.rs
src/commands/restack.rs
src/commands/smartlog.rs
src/commands/undo.rs
src/commands/wrap.rs
src/core/eventlog.rs
src/core/graph.rs
src/core/mergebase.rs
src/core/metadata.rs
src/core/rewrite.rs
src/git/repo.rs
src/main.rs
src/testing.rs
tests/command/test_init.rs
tests/command/test_move.rs
tests/command/test_restack.rs
tests/command/test_wrap.rs
tests/core/test_eventlog.rs

- refactor(repo): create separate `NonZeroOid` and `MaybeZeroOid` types
- feat(rewrite): don't reapply upstream commits for in-memory rebases
- feat(rewrite): don't rebase upstream commits for on-disk rebases

Don't reapply upstream commits

---

.github/workflows/lint.yml

- ci: use Rust 1.53.0 for lints
- ci: use `actions-rs/clippy-check` action

CI changes

---

.github/workflows/lint.yml
CHANGELOG.md
src/commands/move.rs
src/core/formatting.rs
src/core/rewrite/execute.rs
src/core/rewrite/hooks.rs
src/git.rs
src/git/config.rs
src/git/oid.rs
src/git/repo.rs
src/main.rs
tests/command/test_move.rs
tests/command/test_restack.rs

- ci: use Rust 1.53.0 for lints
- ci: use `actions-rs/clippy-check` action
- fix(rewrite): check out rewritten version of commit after `git move`
- fix(rewrite): calculate correct source commit for `git move --base`
- feat(rewrite): change dependency cycle arrowhead glyph
- feat(move): default to `--base HEAD`
- refactor(repo): move `HeadInfo::detach_head` into `Repo`
- cleanup(repo): move `struct Repo`
- refactor(repo): create `oid` module
- feat(move): abort on-disk rebase when there are uncommitted changes

`git move` improvements

---

src/git/repo.rs

repo: parse release candidate Git version strings

---

.github/workflows/linux.yml
CHANGELOG.md
src/commands/undo.rs
src/testing.rs
tests/command/test_undo.rs

Closes #57. Some operations, such as bisecting and stashing, use references in an unconventional way. These are reported as if there is no change to the content of the reference, which might happen e.g. if instead the reflog for that reference was changed, or if it was touched but left unchanged.
These uses for references don't really affect the commit graph. Ideally, we would handle them entirely differently. They should have an entirely separate history, and it should be possible to rewind them separately from the commit graph's history. For example, you should be able to unmark a certain commit during a bisect operation without affecting any commits you may have made since starting the bisect.
The UI for this would need to be considered thoughtfully. Since this isn't too common of a …

fix(undo): report unsupported use-case for empty events

---

.github/workflows/macos.yml
src/testing.rs

- tests: inherit GIT_EXEC_PATH in testing if set
- ci: run macOS build on branches with `macos` in name

macos fix build

---

.github/workflows/linux-git-devel.yml

It would be best to be notified of any issues as early as possible, so that we can send a message to the mailing list. In particular, Git's reference-transaction support is not quite stable, so it might change in an unfortunate way.

ci: test against both Git `master` and `next`

---

.gitpod.yml
.gitpod/Dockerfile
.vscode/settings.json
tests/command/test_wrap.rs

This allows `git-branchless` to be developed and executed in the cloud.

build: create `gitpod.yml`

---

CHANGELOG.md
src/commands/init.rs
src/testing.rs
tests/command/test_init.rs

feat(init): hide GC-related references from `git log` by default

---

src/commands/navigation.rs
src/core/rewrite/execute.rs
src/git.rs
src/git/run.rs
tests/command/test_move.rs
tests/command/test_navigation.rs
tests/command/test_restack.rs

Fixes #182.
- Adds warnings when `next`/`prev`/`checkout` fails to check out the requested commit.
- Adds a warning to `next` when the user requests advancing by more than the number of available children.

feat(navigation): Improve warnings for navigation commands when checkout fails

---

.github/workflows/nix-linux.yml
.github/workflows/nix-macos.yml
flake.nix

As promised in #120.
This introduces a new file `default.nix` at the top-level of the repository. If it is in the way, I can also hide it somewhere else and just move it to the top-level in the CI.
The Nix build is rather slow because it transitively fetches all of the dependencies and nothing is cached paired with general build slowness of Rust. It's possible to obtain some caching but it involves a third-party provider. GitHub itself does not offer a Nix binary cache (yet?).

ci: add Nix build on Linux and macOS

---

CHANGELOG.md
Cargo.toml
bin/entry_points/git-branchless-amend.rs
src/commands/amend.rs
src/commands/init.rs
src/commands/mod.rs
src/git/mod.rs
src/git/repo.rs
src/git/run.rs
src/git/tree.rs
src/opts.rs
src/testing.rs
tests/command/test_amend.rs
tests/mod.rs

Create a new amend command that automatically amends changes to tracked files onto the HEAD commit, and can optionally perform an immediate restack.
(See e.g. #48)

feat(amend): Initial amend command

---

src/commands/init.rs
src/git/repo.rs
src/git/run.rs

Fixes #200.
- `run_silent` now returns stderr, stdout, and exit_code
- `run_silent` now defaults to returning an error if git exits with a nonzero code (though, this behavior can be disabled with an option)

fix(run): Default to treating git failures as errors

---

README.md

Initially, I thought there wasn't any developer documentation, because the Developer Docs section in the Wiki TOC is well-hidden under the long User Docs section. 😅
Highlighting it in the README, so that it is less likely that someone else misses it in the future.

docs: add Contributing section to README

---

.github/workflows/nix-linux.yml
.github/workflows/nix-macos.yml
flake.lock
flake.nix

Currently Nix is only used for CI. With this contribution using the development version of git-branchless will become very ergonomic for Nix users.
For example, Nix users with `experimental-features = nix-command flakes` enabled can now use
```
nix shell github:arxanas/git-branchless
```
to be dropped into a shell where the latest git-branchless is available.
Users who like to be on the bleeding edge can add git-branchless to their flake inputs and use the included overlay to add git-branchless to their profile.
```nix
{
inputs.git-branchless.url = "github:arxanas/git-branchless";
outputs = { self, nixpkgs, git-branchless, ... }:
let
system = "x86_64-linux";
pkgs = import nixpkgs {
inherit system;
overlays = [ git-branchless.overlay ];
};
in {
};
}
```

ci: provide Nix overlay

---

CHANGELOG.md
src/core/rewrite/execute.rs
src/core/rewrite/plan.rs
src/core/rewrite/rewrite_hooks.rs
tests/command/test_move.rs
tests/command/test_restack.rs

fix: override Git's branch moving behavior for on-disk rebases

---

src/commands/init.rs
src/git/config.rs
tests/command/test_init.rs

As per https://github.com/arxanas/git-branchless/issues/219.
This is a simple change to skip adding an alias if it's already defined in the user's default configs ("global, XDG and system configuration files" as per https://docs.rs/git2/latest/git2/struct.Config.html#method.open_default).

fix(init): skip adding aliases to a repo when a user already has that alias defined

---

CHANGELOG.md
src/commands/init.rs

Now doable thanks to https://github.com/arxanas/git-branchless/pull/267.

feat(amend, checkout): re-enable `git amend`/`git checkout` aliases

---

src/testing.rs

My system has a hook installed (for checking for accidentally
committed secrets), which interfered with tests. Let' set
`GIT_CONFIG_NOSYSTEM` to fix that.

tests: ignore system config in tests

---

CHANGELOG.md
src/commands/bug_report.rs
src/commands/mod.rs
src/commands/navigation.rs
src/commands/smartlog.rs
src/commands/undo.rs
src/opts.rs
tests/command/test_init.rs
tests/command/test_smartlog.rs

I believe that this implements an `--only-branches` flag for `smartlog`. This is my first time using Rust (hence the "I believe" part), so any comments or suggestions to make this more idiomatic for rust or the project are warmly welcomed. Also, I was 100% like `\o/` "it compiles!" :smile:
This includes a test, and I've wired up all of the connections that I was able to discern by looking at examples from other commands, etc. Please let me know if I missed something, or should remove any of it.
The logic change was actually pretty easy: instead of `observed_commits.difference(obsolete_commits)`, I only needed to do `observed_commits.intersection(branch_commits)`, so no changes were needed for `query_active_heads` as discussed in #283. *That said*, though this is passing the tests and the …

feat(smartlog): add `--only-branches` flag

---

src/git/run.rs
src/testing.rs

When I ran the tests with `LANG=sv_SE.UTF-8` exported in my shell,
`test_run_silent_failures` failed. This patch fixes it. yujong-lee@
reported many more language-related failures but I wasn't able to
reproduce those.

tests: don't propagate environment into `GitRunInfo`

---

CHANGELOG.md
src/core/node_descriptors.rs
src/git/repo.rs
src/git/run.rs
tests/command/test_amend.rs
tests/command/test_bug_report.rs
tests/command/test_hide.rs
tests/command/test_init.rs
tests/command/test_move.rs
tests/command/test_navigation.rs
tests/command/test_restack.rs
tests/command/test_smartlog.rs
tests/command/test_sync.rs
tests/command/test_undo.rs
tests/core/test_gc.rs
tests/core/test_hooks.rs
tests/test_branchless.rs

I am interested in this project and I want to contribute to code although I'm not good at rust. I think I can be better by contributing this project.
Can you help me with this?
I was trying to pick up #280.
I thought `oid` in this function should be calculated using `git2`.
https://github.com/arxanas/git-branchless/blob/45ace45579804697f8daeb551750424bf8e8538b/src/core/node_descriptors.rs#L183-L199
Then I might have to change constructor.
https://github.com/arxanas/git-branchless/blob/45ace45579804697f8daeb551750424bf8e8538b/src/core/node_descriptors.rs#L178
So my current status in ccc277c37c6f138bb17e2d0ac19898bcc82fc3f3 is I brought `&Repo` to constructor.
```rust
pub fn new(repo: &Repo, use_color: bool) -> eyre::Result<Self> {
Ok(CommitOidDescriptor { use_color })
}
```
And I got 3 …

Use git2 hash-shortening function

---

CHANGELOG.md
Cargo.lock
Cargo.toml
src/commands/init.rs
src/commands/mod.rs
src/commands/move.rs
src/commands/restack.rs
src/commands/reword.rs
src/commands/sync.rs
src/core/config.rs
src/core/rewrite/execute.rs
src/core/rewrite/plan.rs
src/git/mod.rs
src/git/repo.rs
src/opts.rs
tests/command/test_move.rs
tests/command/test_reword.rs
tests/mod.rs

**Updated PR description:**
This supports all of the use-cases that [I mentioned on #179](https://github.com/arxanas/git-branchless/issues/179#issuecomment-1071087014), except for the fancy bulk editing case. That is to say:
- Reword single or multiple commits within or across subtrees.
- Currently, the same message is applied to all commits.
- If multiple message flags are given on the CLI, they are combined into separate paragraphs.
- If no message flags are passed on the CLI, `$EDITOR` is opened w/ either the message of the commit being reworded (if just rewording a single commit) or a stub message when rewording multiple commits.
- Bails out if the edited message is identical to the input message, or if it's blank.
A few things to make special note of:
-  I'm still *very much* …

feat: implement `git reword` command (#179)

---

Cargo.lock
src/core/effects.rs

Supersedes https://github.com/arxanas/git-branchless/pull/321. Closes #317.

build: bump indicatif from 0.17.0-beta.1 to 0.17.0-rc.10

---

git-branchless/src/commands/undo.rs
git-branchless/tests/command/test_undo.rs

fix(undo): show up-to-date smartlog after `git undo`

---

CHANGELOG.md
Cargo.lock
git-branchless-lib/src/git/repo.rs
git-branchless/Cargo.toml
git-branchless/src/commands/reword.rs

This implements a bulk editing mode for `git reword`, as discussed in #179. I feel pretty good about the features, but I'm still learning Rust and it feels like there is still some clean up needed for some of the implementation code, though to be honest *exactly what* clean up is needed isn't entirely clear to me right now. Some of it just has a subtle smell to it, like there's a simpler way that I'm not yet familiar with. Any pointers would be appreciated!
The format of the bulk edit message is as discussed in #179, and is very similar to `git revise` (though I've yet to use `revise`):
```
++ reword <commit 1 hash>
<commit 1 message>
++ reword <commit 2 hash>
<commit 2 message>
```
When called with `--discard`, the original messages are included (commented out) along w/ the commit …

feat(reword): implement bulk editting mode

---

git-branchless-lib/src/core/dag.rs

> Oops, I wrote CommitSet::from_iter(foo.collect()) but it should be just foo.collect(). Anyways, you can leave this as is, and I'll update this site and the other uses in the codebase to use .collect() later.
Is this what you had in mind over at https://github.com/arxanas/git-branchless/pull/366#discussion_r858156321?
Out of curiosity, do you generally prefer `let ... : CommitSet = ... .collect()` or `let ... = ... collect::<CommitSet>()`? Or does it depend on the context? My understanding ATM is that they're roughly equivalent ways of nudging the compiler towards the desired type, right?

refactor(dag): `CommitSet::from_iter()` -> `collect::<CommitSet>()`

---

.github/workflows/nix-linux.yml
.github/workflows/nix-macos.yml

This should avoid surprises like martinvonz/jj#299, I hope.

ci: don't override nixpkgs version (use the lock file's version)

---

git-branchless/src/commands/hide.rs
git-branchless/src/commands/mod.rs
git-branchless/src/opts.rs
git-branchless/tests/command/test_hide.rs
git-branchless/tests/test_branchless.rs

Changes in this PR:
- Display a list of branches abandoned during a `git hide` operation
- Add `-D/--delete-branches` flag to delete branches abandoned during a `git hide` operation
- The `-D` short flag was chosen for parity w/ `git branch -D <branch name>`
See discussion at https://github.com/arxanas/git-branchless/discussions/283#discussioncomment-2298871

feat(hide): Display (and optionally delete) abandoned branches

---

flake.lock

Bumps the version of nixpkgs to https://github.com/NixOS/nixpkgs/commit/e0169d7a9d324afebf5679551407756c77af8930 which is the current HEAD of the nixos-unstable branch. This will change the default version of Rust to 1.61.0 for the Nix build.

ci: bump nixpkgs version

---

CHANGELOG.md
git-branchless-lib/src/git/repo.rs
git-branchless/src/commands/hide.rs
git-branchless/tests/command/test_hide.rs

This is a stab at #423; does this look like it would handle the issue you encountered? I admit that I didn't explore the area too much to see if there might be other issues lurking.
Question: Is `check_out::check_out_commit()` the right way to go about this?
This is draft b/c I still need to deal w/ the `_exit_code` from `check_out_commit()`. I'm thinking that we'll throw an error explaining the situation if `!exit_code.is_success()`, but I've never dealt with unborn branches, so I'm not familiar with recovery from that state. I'll tinker this weekend and push what I come up with.

fix(hide): Checkout commit of deleted HEAD branch (close #423)

---

git-branchless-lib/src/core/dag.rs
git-branchless-lib/src/core/gc.rs
git-branchless-lib/src/core/rewrite/plan.rs
git-branchless/src/commands/move.rs
git-branchless/src/commands/query.rs
git-branchless/src/commands/restack.rs
git-branchless/src/commands/smartlog.rs
git-branchless/src/revset/eval.rs
git-branchless/src/revset/resolve.rs
git-branchless/tests/command/test_move.rs
git-branchless/tests/core/test_gc.rs

Closes #412. With this stack, any commit which appears in `git smartlog` should be marked as reachable for GC, regardless of where it came from.

Garbage collection reachability improvements

---

CHANGELOG.md
git-branchless-lib/src/core/dag.rs
git-branchless/src/commands/mod.rs
git-branchless/src/commands/move.rs
git-branchless/src/opts.rs
git-branchless/tests/command/test_move.rs

_[reopening #448]_
Still a WIP, but seems to be working. I've rebased my work onto #447 (which is also WIP) and I'll update this as that PR develops. I'll probably add some more tests, too, as I wrote all of these w/ a pre-revset mindset, so I was only thinking about moving single ranges/commits. 
- ~~Adds a `git move --range <revset>` option to move ranges of commits.~~
- Adds a `git move --exact <revset>` option (shorthand: `-x`) to move single commits and/or ranges of commits.
- Updates CHANGELOG for #400, #447 and #448

`git move`: Add `--exact` option (closes #176)

---

README.md

Replace markdown code markup with HTML as it can't be recognized when interleaved with the latter.
Also changed `git rebase -i` to `git rebase --interactive` to be more clear and consistent with the content above (`git log --graph`).

docs: fix inline code markup

---

CHANGELOG.md
git-branchless-lib/src/core/formatting.rs
git-branchless/src/opts.rs

fix(smartlog): respect `--color always`

---

CHANGELOG.md
git-branchless/src/revset/builtins.rs
git-branchless/src/revset/eval.rs
git-branchless/tests/command/test_query.rs

As discussed in discord, this adds an `exactly` revset function. This returns the given revset only if it contains the expected number of commits. Otherwise it errors out. This was very straightforward to implement and includes tests.
**Notes**
- I considered creating a more general usage `count` function that would behave like the text/date matchers, for example:
- `count(<revset>, exactly:1)`
- `count(<revset>, greater_than:2)`
- `count(<revset>, less_than_or_equal_to:3)`, etc. 
- While that would be cool, it was more than I needed at this time.
- At first I had also added a `sole()` function, but I removed that in favor of making it an alias for `exactly($1, 1)` using the revset aliases PR.
- I have already found this useful in scripting to give me added confidence that some automated …

feat(revset): Add `exactly` function

---

CHANGELOG.md
git-branchless/src/revset/eval.rs
git-branchless/src/revset/pattern.rs

As discussed in discord, this trims ending newlines from commit messages when they are compared with `message()`. In particular, this provides for more intuitive (to me) usage of `message(exact:...)` and `message(regex:...)` because I feel that most folks would assume that the commit message would not include the trailing newline anyway. This is a 1 line change and includes supporting tests.
Behavior without this change (on `master`):
```sh
❯ git commit -am 'My commit'
❯ git query 'message(exact:My commit)'
❯ git query 'message(regex:My commit$)'
❯ git query 'message(exact:My commit\n)'
abc123 My commit
❯ git query 'message(regex:My commit\n$)'
abc123 My commit
```
With this change:
```sh
❯ git commit -am 'My commit'
❯ git query 'message(exact:My commit)'
abc123 My commit
❯ git query …
```

fix(revset): Ignore ending newline in `message(...)`

---

CHANGELOG.md
git-branchless/src/revset/ast.rs
git-branchless/src/revset/eval.rs

This was fun to implement, and was pretty easy. Considering how flexible and powerful it could be ... I'm sort of concerned I'm overlooking something! 😄  As always, I'm 100% open to suggestions here.
- This does nothing to check for -- let alone prevent -- recursion in aliases. If someone defines a `foo` alias that itself calls `foo()` ... they're out of luck.
- This only allows aliasing functions; I did not consider allowing aliases for names, though it would be easy to add. 
- I kind of feel like it's not necessary, though. Aliasing names risks conflicting w/ commits and refs, while functions have no such conflict. And aliases feel a little more "functiony" anyway.
- I made no attempt to include the defined aliases in the `EvalError::UnboundFunction` output. It wasn't immediately …

feat(revset): Support custom revset aliases

---

git-branchless-lib/src/core/rewrite/plan.rs
git-branchless/tests/command/test_move.rs

I think this fixes (one of) the issue raised in #515: the error message displayed when attempting to rewrite public commits was out of sync w/ the actual name of the flag.

Display correct flag name about rewriting public commits (#515)

---

CHANGELOG.md
git-branchless/src/commands/mod.rs
git-branchless/src/commands/reword.rs
git-branchless/src/opts.rs
git-branchless/tests/command/test_reword.rs

This adds a `--fixup` option to `git reword`, providing a convenient way to turn existing commits into `fixup!` commit. With this, instead of doing something like `git reword <commits to reword> -m 'fixup! <paste title of commit to fixup>'`, you can now do `git reword <commits to reword> --fixup <commit to fixup>` and `reword` will handle the rest, including some error checking.
I've been using this for a few weeks and it's been working well. My only remaining concern about this is that the CLI option docs and error messages feel a little clunky because it's hard to talk to about "the commit being fixed up" vs "the commits that will become `fixup!` commits". As usual, suggestions are welcome!

feat(reword): Add `--fixup` flag to `git branchless reword`

---

git-branchless-lib/src/git/repo.rs

I believe this is what was intended.  I think the linter caught a genuine error here, because I believe `0` actually would refer to `commit` here.  At least that's what the linter suggests would be equivalent.  Guessing maybe the map gets sorted alphabetically, so then `0` would refer to `commit`?
Looks like there's no tests for this error message, though, as the tests passed whether I put `{commit}` or `{source}` here

Fix lint error

---

git-branchless/src/commands/submit.rs
git-branchless/tests/command/test_submit.rs

This PR avoids trying to create new branches when there are no new branches to create
Fixes #557

Fix `submit --create` with no new remote branches

---

git-branchless/src/revset/grammar.lalrpop
git-branchless/src/revset/parser.rs

Add support for parentheses anywhere in revsets
Fixes #558

Fix revset parentheses

---

flake.nix
git-branchless-lib/src/core/check_out.rs
git-branchless-lib/src/core/config.rs
git-branchless/tests/command/test_move.rs
git-branchless/tests/command/test_navigation.rs
git-branchless/tests/command/test_reword.rs
git-branchless/tests/command/test_undo.rs
git-branchless/tests/test_branchless.rs

This is a follow-up from [the discussion here](https://github.com/arxanas/git-branchless/discussions/520#discussioncomment-3603617). It updates the `git co` command to check if the selected commit is associated with a single branch, and checks that out if so.

Add support for interactively checking out a branch

---

git-branchless/src/revset/builtins.rs
git-branchless/src/revset/eval.rs
git-branchless/tests/command/test_query.rs

This is my first take on a `rewritten()` revset that resolves possibly-outdated commit hashes into their most current version. First discussed here https://github.com/arxanas/git-branchless/discussions/48#discussioncomment-3718889
The primary use case is being able to do things like `git move -x abc123 -d deb456 && git reword 'rewritten(abc123)'`, ie to avoid having to lookup the new SHA of the moved commit. If I understand the docs of `find_rewrite_target()` correctly, this should be able to work across many rebase/move/reword/restack/etc operations, so long as the specified SHA hasn't been gc'd.
I have only exercised this a little bit, so I'm not 100% certain of the implementation. I also note that there's *a lot* of `.wrap_err("...").map_err(EvalError::OtherError)` going on in here. …

feat(revset): Add `rewritten` revset function

---

git-branchless-lib/src/core/repo_ext.rs
git-branchless-lib/src/git/repo.rs
git-branchless-lib/src/testing.rs
git-branchless/src/commands/init.rs
git-branchless/tests/command/test_init.rs

Improvements to `git init`

---

git-branchless/src/opts.rs
git-branchless/tests/command/test_navigation.rs

`git branch` uses `--branch` to create a new branch, but `git switch` uses `--create`. This PR changes `git-branchless switch` to match `git switch`.

feat(switch): change `--branch` to `--create`

---

git-branchless-lib/src/core/dag.rs
git-branchless-lib/src/core/rewrite/evolve.rs
git-branchless-lib/src/core/rewrite/plan.rs
git-branchless/src/commands/hide.rs
git-branchless/src/commands/move.rs
git-branchless/src/commands/navigation.rs
git-branchless/src/commands/smartlog.rs
git-branchless/src/revset/builtins.rs
git-branchless/src/revset/eval.rs
git-branchless/src/revset/pattern.rs

Fix performance regression

---

git-branchless-lib/src/testing.rs
git-branchless/tests/test_git.rs

This ensures that users are not running Git through a wrapper such as the following:
```zsh
#!/usr/bin/zsh
exec git "$@"
```
Running Git through a wrapper like this causes some very interesting behaviour and many test failures (at least on my Linux machine):
- Zsh automatically sets the `HOME` environment variable, causing the Git global config to leak into tests. This causes confusing test failures as the global config is assumed to be empty in tests (as `$HOME` should not be set).
- Zsh automatically sources `~/.profile`, so if Cargo was installed locally (as recommended), `~/.profile` will source a script to add `$HOME/.cargo/bin` to the `PATH` environment variable if it exists. Therefore, the `git` command run by the wrapper would use the local Cargo installation of `git-branchless` …

tests: ensure Git executable does not have a global config

---

git-branchless-opts/src/lib.rs
git-branchless/src/commands/hooks.rs
git-branchless/src/commands/init.rs
git-branchless/src/commands/mod.rs
git-branchless/tests/test_bug_report.rs
git-branchless/tests/test_hooks.rs
git-branchless/tests/test_init.rs
git-branchless/tests/test_sync.rs

fix(init): install `post-applypatch` hook

---

git-branchless-lib/src/core/config.rs

Using --type path will automatically take care of tilde and `%(prefix)` expansion. Fix #731.

fix(init): expand tilde from core.hooksPath

---

git-branchless-lib/src/core/rewrite/execute.rs
git-branchless-lib/src/git/reference.rs
git-branchless-lib/src/git/repo.rs
git-branchless/tests/test_move.rs

fix(rewrite): delete branch configuration along with branches

---

git-branchless-lib/src/git/repo.rs

Calling .into_iter() in this context is a no-op and is flagged by clippy.

style: diff.deltas() is already an iterator

---

Cargo.lock
git-branchless/Cargo.toml
git-branchless/src/commands/amend.rs
git-branchless/tests/test_amend.rs

fix(amend): don't amend children onto grandparent commits

---

git-branchless-lib/src/core/check_out.rs
git-branchless-navigation/src/lib.rs
git-branchless-opts/src/lib.rs
git-branchless/tests/test_navigation.rs
git-branchless/tests/test_record.rs

feat(switch): add `--detach` flag to `git branchless switch`

---

git-branchless-reword/src/dialoguer_edit.rs

Name the tempfile used by `git reword` `COMMIT_EDITMSG-*.txt`, aligning with the naming of `.git/COMMIT_EDITMSG`. This makes it easier to configure editors to apply syntax highlighting without false positives.

feat(reword): Use distinctive name for tempfile

---

git-branchless-lib/src/core/effects.rs
git-branchless-lib/src/core/formatting.rs
git-branchless-opts/src/lib.rs
git-branchless-smartlog/src/lib.rs
git-branchless-smartlog/tests/test_smartlog.rs
git-branchless/tests/test_init.rs

This pull request adds a flag for reverse-chronological smartlog output. 😈 As far as I can tell, all that's needed is to swap the `split` and `merge` glyphs and then to reverse the order when outputting the smartlog line by line.
I've continued to emit hints at the end of the output, mostly just because that was the path of least resistance. I'm agnostic on whether it would make sense to move them to the top.

feat(smartlog): add --reverse option

---

Cargo.lock
Cargo.toml
scm-record/Cargo.toml
scm-record/examples/static_contents.rs
scm-record/src/lib.rs
scm-record/src/render.rs
scm-record/src/types.rs
scm-record/src/ui.rs
scm-record/src/util.rs

This is a replacement for the existing `git-record` library, which doesn't perform well. The approach is to use `tui` instead of `cursive`, which requires that we implement a lot more by hand, but also should be more performant.

Create `scm-record` library

---

git-branchless-lib/src/testing.rs

Users can have a value for core.abbrev different than the default one in their ~/.gitconfig, this makes some tests fail because when comparing the output, they expect hashes to be 7 chars long. Fix by setting an explicit value of 7 when initializing a repo inside a test.

tests: set an explicit value for core.abbrev config

---

git-branchless-submit/src/lib.rs
git-branchless-submit/tests/test_submit.rs

This is a follow up from my question in https://github.com/arxanas/git-branchless/discussions/671. I have made the changes to only fetch branches that are being pushed. I am testing it locally now and so far it seems to behave as expected but I am not sure if there are other edge cases to consider. I will continue to use this build for a few days and see if I encounter any other issues, but I figured it would be good to just open the MR for feedback first.
Thank you.
EDIT: not sure why the tests are failing for windows. They are passing on my machine.
EDIT2: I was not running tests for the entire workspace. Fixed.

Limit fetch in submit to relevant branches

---

git-branchless-init/src/lib.rs
git-branchless-opts/src/lib.rs
git-branchless/src/commands/mod.rs
git-branchless/tests/test_init.rs

feat(init): create `install-man-pages` subcommand

---

README.md

With v0.7.1 I am migrating `git-branchless` [to the official repositories for Arch Linux](https://archlinux.org/packages/community/x86_64/git-branchless/). That makes quite a few platforms with prebuilt packages now. I would suggest that *if* the user is on a system with system packages available that is almost certainly a better path for them than directly compiling and installing via `cargo` (completions, access from other users, automatic upgrades, etc.). As such I suggest suggesting it in the "short version" of how to install.

docs: Suggest checking package repositories before cargo install

---

git-branchless-revset/src/pattern.rs

This actually doesn't fix the issue in which large sets are evaluated during the intersection operation, but I figure I'd better commit this before I forget.

fix(revset): set `Flags::FILTER` on evaluate/contains sets

---

git-branchless-lib/src/core/rewrite/plan.rs
git-branchless-lib/tests/test_rewrite_plan.rs
git-branchless/tests/test_move.rs

fix(rewrite): fix cases of moving all parents of merge commits

---

Cargo.lock
git-branchless-lib/bin/testing/regression_test_record.rs
git-branchless-lib/src/git/diff.rs
scm-record/Cargo.toml
scm-record/benches/benches.rs
scm-record/examples/static_contents.rs
scm-record/src/bin/scm-diff-editor.rs
scm-record/src/types.rs
scm-record/src/ui.rs
scm-record/tests/test_scm_record.rs

This PR creates the `scm-diff-editor` binary, a TUI application for selecting subsets of changes in a diff. It can be used with `jj` as the `diff-editor` to facilitate commands like `jj move` and `jj split`.
To install the `scm-diff-editor` binary:
```sh
$ cargo install --git https://github.com/arxanas/git-branchless --branch scm-diff-editor scm-record --features scm-diff-editor
```
Then set the following in your `jjconfig.toml`:
```toml
[ui]
diff-editor = ["scm-diff-editor", "--dir-diff", "$left", "$right"]
```

`scm-diff-editor` binary

---

scm-record/src/types.rs
scm-record/src/ui.rs
scm-record/tests/test_scm_record.rs

This copies a feature from hg's record interface. It's most often useful before you do anything, to select all lines.

feat(record:scm-diff-editor): add key "a" for toggling all selections

---

git-branchless-hook/src/lib.rs

As discussed on [discord](https://discord.com/channels/915309546984050709/915309546984050712/1108952258877599855), this suppresses the warnings generated when `branchless` encounters a peeled ref while parsing the `packed-refs` file. This does make any attempt to process these refs correctly, which -- as I understand it -- would be to associate there OIDs with the preceding "normal" ref.

feat(hooks): Suppress warning for peeled refs while parsing packed-refs

---

git-branchless-lib/src/core/dag.rs

This resolves a clippy warning introduced in Rust 1.71.

chore(clippy): Use reference instead of Borrow

---

git-branchless-lib/src/core/rewrite/execute.rs
git-branchless-lib/src/core/rewrite/plan.rs
git-branchless-lib/src/git/mod.rs
git-branchless-lib/src/git/repo.rs
git-branchless-lib/tests/test_rewrite_plan.rs
git-branchless-move/src/lib.rs
git-branchless-opts/src/lib.rs
git-branchless-testing/src/lib.rs
git-branchless/src/commands/amend.rs
git-branchless/src/commands/mod.rs
git-branchless/tests/test_move.rs

**Summary**  
As the title says, this adds a `move --fixup` flag to squash commits into the destination, in memory or on disk. With this, both of these use cases:
- `rebase -i` + reordering & marking as `fixup!`
- `reword --fixup <dest> <revset> ; rebase -i --autosquash`
Can be replaced with just
- `move -d <dest> -x <revset> --fixup`
Add'l examples:
- Oops, used `commit` instead of `amend`, lets squash HEAD into it's parent: `move -d @~ -x @ --fixup`
- Squash a branch onto a single commit: `move -d head(stack()) -s children(head(stack())) --fixup`
- Useful perhaps for cases like https://github.com/arxanas/git-branchless/discussions/965#discussioncomment-6453119
The original idea came from https://github.com/arxanas/git-branchless/pull/538#pullrequestreview-1105180957 and it's taken me …

feat(move): Add `--fixup` to squash moved commits into the destination

---

CHANGELOG.md

Accidentally closed https://github.com/arxanas/git-branchless/pull/1028 — I thought that merging the base PR would update the target branch, but it seems like that only happens if a single person owns both PRs. Anyways, I reordered the changelog items to be in PR number order

docs: Add `move --fixup` to CHANGELOG.md

---

scm-record/src/types.rs

scm-record: fix build without `serde` feature

---

.github/workflows/release.yml

The release script was trying to copy LICENSE, which no longer exists. Instead copy the new LICENSE-APACHE and LICENSE-MIT. I'm hopeful this will fix the issue mentioned in the v0.8.0 [release discussion](https://github.com/arxanas/git-branchless/discussions/1052#discussioncomment-6913309), shown [here in the GitHub Actions log](https://github.com/arxanas/git-branchless/actions/runs/6040012495/job/16389940594#step:6:19):

Fix release for new license files

---

Cargo.toml
git-branchless-hook/tests/test_hook.rs
git-branchless-init/src/lib.rs
git-branchless-lib/src/core/config.rs
git-branchless-lib/src/core/dag.rs
git-branchless-lib/src/core/effects.rs
git-branchless-lib/src/core/eventlog.rs
git-branchless-lib/src/core/rewrite/rewrite_hooks.rs
git-branchless-lib/src/git/repo.rs
git-branchless-lib/src/git/run.rs
git-branchless-lib/src/git/test.rs
git-branchless-lib/src/testing.rs
git-branchless-lib/tests/test_eventlog.rs
git-branchless-lib/tests/test_repo.rs
git-branchless-revset/src/builtins.rs
git-branchless-submit/src/lib.rs
git-branchless-submit/src/phabricator.rs
git-branchless-submit/tests/test_phabricator_forge.rs
git-branchless-test/src/lib.rs
git-branchless/src/commands/bug_report.rs
git-branchless/tests/test_bug_report.rs
git-branchless/tests/test_eventlog.rs
git-branchless/tests/test_gc.rs
git-branchless/tests/test_hooks.rs
git-branchless/tests/test_init.rs
git-branchless/tests/test_move.rs
git-branchless/tests/test_wrap.rs

fix(hooks): use same `branchless` dir for all worktrees

---

CHANGELOG.md
git-branchless-opts/src/lib.rs
git-branchless-submit/src/lib.rs
git-branchless-submit/tests/test_submit.rs

`submit` is inherently side effecting in non-obvious-to-undo ways. This is a rudimentary attempt to add a `--dry-run` flag to see what `submit` would be trying to do.

feat(submit): add --dry-run flag

---

CHANGELOG.md
git-branchless/src/commands/sync.rs
git-branchless/tests/test_sync.rs

feat(sync): resolve revset arguments to their entire stacks

---

CHANGELOG.md
git-branchless-lib/src/git/status.rs
git-branchless-lib/tests/test_status.rs
git-branchless/tests/test_amend.rs

The regex in `StatusEntry::try_from()` was mistaken parsing status lines for files with spaces in such a way to discard the first word in the path name. This attempts to make that less likely by making the regex more specific, but I don't think it's really unavoidable without completely reworking this part of the code to be less flexible. eg if we parsed each of the 1/2/u statuses separately, then we could be more specific about how many fields we need to match/capture for each option.
I suspect that this issue was already rare, and that this fix will make it even moreso. Given that, I feel like a more robust/complex fix probably isn't warranted. With this fix, files like "r101 project.txt" or "Coffee notes.txt" will work, but "R101 project.txt" or "coffee notes.txt" ("R101" looks like a …

fix(status): rudimentary support for filenames with spaces

---

.github/workflows/lint.yml
git-branchless-lib/src/core/effects.rs
git-branchless-lib/src/git/index.rs
git-branchless-lib/tests/test_eventlog.rs
scm-record/src/util.rs

**Stack:**
* https://github.com/arxanas/git-branchless/pull/1170
---
cleanup: fix `cargo clippy`

[1/1] cleanup: fix `cargo clippy`

---

git-branchless-record/src/lib.rs
git-branchless-record/tests/test_record.rs
git-branchless-reword/src/lib.rs

**Stack:**
* https://github.com/arxanas/git-branchless/pull/1167
* https://github.com/arxanas/git-branchless/pull/1171
* https://github.com/arxanas/git-branchless/pull/1173
* https://github.com/arxanas/git-branchless/pull/1172
* [5/16] refactor(dag): extract `query_stack_commits` to `Dag`
* [6/16] feat(git): export `GitErrorCode` from `repo`
* [7/16] feat(submit): create `SubmitStatus::Local`
* [8/16] feat(submit): make forges branch-agnostic
* [9/16] feat(git): add `Branch::rename` method
* [10/16] testing: configure repos cloned with `Git::clone_repo_into`
* [11/16] wip: some `GithubForge` implementation
* [12/16] wip: more Github forge
* [13/16] wip: update `commit_summary_slug`
* [14/16] feat(submit:github): auto-select Github forge when `gh repo set-default` has been used
* [15/16] …

[1/16] feat(record): use commit message template in inline message editor

---

git-branchless-opts/src/lib.rs
git-branchless-record/src/lib.rs
git-branchless-record/tests/test_record.rs

Because I need to stash things and `git stash` falls short I've created this PR. Fixes #979.

feat(record): add --stash flag

---

git-branchless-test/src/lib.rs
scm-bisect/src/search.rs

**Stack:**
* https://github.com/arxanas/git-branchless/pull/1174
* https://github.com/arxanas/git-branchless/pull/1175
* https://github.com/arxanas/git-branchless/pull/1176
* https://github.com/arxanas/git-branchless/pull/1177
* https://github.com/arxanas/git-branchless/pull/1162
---
refactor(bisect): rename `search::SearchGraph` -> `search::Graph`
For uniformity with the other symbols in this module (`Strategy` etc.).

[1/5] refactor(bisect): rename `search::SearchGraph` -> `search::Graph`

---

CHANGELOG.md
git-branchless-lib/src/testing.rs
git-branchless-opts/src/lib.rs
git-branchless-record/src/lib.rs
git-branchless-record/tests/test_record.rs

This is a minor QOL improvement, and should bring `record` in line with how `commit` and `reword` accept multiple `-m/--message` args, turning them into multiple paragraphs in the commit message.

feat(record): allow multiple --message args

---

CHANGELOG.md
git-branchless-lib/src/core/check_out.rs
git-branchless-lib/src/core/repo_ext.rs
git-branchless-lib/src/core/rewrite/execute.rs
git-branchless-lib/src/git/reference.rs
git-branchless-query/tests/test_query.rs
git-branchless-record/src/lib.rs
git-branchless-revset/src/builtins.rs
git-branchless-revset/src/eval.rs
git-branchless-revset/src/pattern.rs
git-branchless-submit/src/branch_forge.rs
git-branchless-undo/src/lib.rs

- I have found `merges()` to be useful, in particular on public commits.
- for `branches(<pattern>)` see #1117
- ~~`branches(<pattern>)` needs more work; it's currently mush slower that I would expect, and it seems to not match some branchs (at least it didn't match all the branches I expected when I used it to push these recent PRs)~~ **Edit:** I believe that this is fixed.

feat(revsets): add `merges()` and allow `branches()` to filter branch names

---

git-branchless-test/src/lib.rs
scm-bisect/proptest-regressions/basic.txt
scm-bisect/src/basic.rs
scm-bisect/src/search.rs

**Stack:**
* https://github.com/arxanas/git-branchless/pull/1176
* https://github.com/arxanas/git-branchless/pull/1177
* https://github.com/arxanas/git-branchless/pull/1162
---
feat(bisect): lift the binary search's speculation to `Search`
Previously, `midpoint` returned an iterator of next nodes to search, which is meant to support speculative searching. This was implemented only for the basic binary search. It could be tedious and error-prone to implement speculation by one's self, so it would be preferable if the library could do it instead. This commit lifts the speculation out of the binary search and into `Search`.
Now, `midpoint` returns a single next node to search, which is substantially easier for implementors (for example, the implementation of binary search is now simply …

[3/3] feat(bisect): lift the binary search's speculation to `Search`

---

git-branchless-reword/src/lib.rs

The first line will be 71 chars if there is only one commit, and >=74 chars if there are multiple commits - which is close enough to 72, and avoids splitting up "these 2 commits" into its own line.

fix(reword): Wrap rewording instructions to 72 chars

---

git-branchless-reword/src/lib.rs

Both arms of the match results in a `&mut Editor` pointing to the same editor, which is redundant.

cleanup(reword): Remove redundant reassignment in `edit_message`

---

git-branchless-lib/src/core/dag.rs
git-branchless-lib/src/git/mod.rs
git-branchless-lib/src/git/reference.rs
git-branchless-lib/src/git/repo.rs
git-branchless-lib/src/testing.rs
git-branchless-revset/src/builtins.rs
git-branchless-submit/src/branch_forge.rs
git-branchless-submit/src/lib.rs
git-branchless-submit/src/phabricator.rs
git-branchless-submit/tests/test_phabricator_forge.rs
git-branchless-submit/tests/test_submit.rs
scm-bisect/examples/guessing_game.rs
scm-bisect/src/basic.rs
scm-bisect/src/search.rs

[9/15] refactor(dag): update some multi-parameter function argument names

---

git-branchless-lib/src/core/dag.rs
git-branchless-lib/src/git/mod.rs
git-branchless-lib/src/git/repo.rs
git-branchless-revset/src/builtins.rs
scm-bisect/examples/guessing_game.rs
scm-bisect/src/basic.rs
scm-bisect/src/search.rs

[4/15] feat(git): export `GitErrorCode` from `repo`

---

git-branchless-lib/src/core/dag.rs
git-branchless-revset/src/builtins.rs
scm-bisect/examples/guessing_game.rs
scm-bisect/src/basic.rs
scm-bisect/src/search.rs

[3/15] refactor(dag): extract `query_stack_commits` to `Dag`

---

scm-bisect/examples/guessing_game.rs
scm-bisect/src/basic.rs
scm-bisect/src/search.rs

[2/15] refactor(bisect): pass `Bounds` to `Strategy::midpoint`

---

git-branchless-lib/src/core/dag.rs
git-branchless-lib/src/git/mod.rs
git-branchless-lib/src/git/reference.rs
git-branchless-lib/src/git/repo.rs
git-branchless-lib/src/testing.rs
git-branchless-revset/src/builtins.rs
git-branchless-submit/src/branch_forge.rs
git-branchless-submit/src/lib.rs
git-branchless-submit/src/phabricator.rs
git-branchless-submit/tests/test_phabricator_forge.rs
git-branchless-submit/tests/test_submit.rs
scm-bisect/examples/guessing_game.proptest-regressions
scm-bisect/examples/guessing_game.rs
scm-bisect/src/basic.rs
scm-bisect/src/search.rs

[1/15] feat(bisect): add guessing game example

---

git-branchless-lib/src/core/formatting.rs

**Stack:**
---
feat(smartlog): switch from `⊘` to `◌` for synthetic omitted-commit nodes
This seems like a strictly more understandable icon. (Originally suggested by @martinvonz for jj.)

[1/2] feat(smartlog): switch from `⊘` to `◌` for synthetic omitted-commit nodes

---

git-branchless-lib/src/testing.rs

**Stack:**
---
testing: forward `RUST_LOG` environment variable
Typically this would be used as `RUST_LOG=git_branchless=debug` or similar.

[1/2] testing: forward `RUST_LOG` environment variable

---

git-branchless-lib/src/testing.rs

**Stack:**
* https://github.com/arxanas/git-branchless/pull/1243
---
Revert "testing: forward `RUST_LOG` environment variable" for Nix's sake
This reverts commit aff490b3477b29119dcba8431bee9ac22d2564ab. That commit seems to cause Nix build failures for some reason that I don't want to diagnose at present.
Example logs (https://github.com/arxanas/git-branchless/actions/runs/7902491612/job/21568284520):
```
git-branchless> ---- test_init_basic stdout ----
git-branchless> ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Snapshot Summary ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
git-branchless> Snapshot: init_basic
git-branchless> Source: git-branchless/tests/test_init.rs:221
git-branchless> ────────────────────────────────────────────────────────────────────────────────
git-branchless> Expression: stderr …
```

[1/1] Revert "testing: forward `RUST_LOG` environment variable" for Nix's sake

---

CHANGELOG.md
git-branchless-opts/src/lib.rs
git-branchless-submit/src/lib.rs
git-branchless-submit/tests/test_submit.rs

I have a bunch of stale branches that I don't want to think about while I work on newer stuff, so I often find myself running `git sync branch-1 branch-2 ...` and then `git submit branch-1 branch-2 ...` ... only for `submit` to tell me that it doesn't support multiple args. 😢  I usually resort to concating them to `branch-1+branch-2+...`, but I would prefer `submit` to do that for me, so here we are. 😄

feat(submit): support multiple revset arguments

---

git-branchless-lib/src/core/eventlog.rs
git-branchless-lib/src/testing.rs
git-branchless-lib/tests/test_eventlog.rs
git-branchless/tests/test_bug_report.rs
git-branchless/tests/test_eventlog.rs
git-branchless/tests/test_hooks.rs
git-branchless/tests/test_undo.rs
git-branchless/tests/test_wrap.rs

**Stack:**
* https://github.com/arxanas/git-branchless/pull/1245
---
tests: Try to fix failing `git-next` tests

[1/1] tests: Try to fix failing `git-next` tests

---

Cargo.lock
git-branchless-lib/src/git/reference.rs
git-branchless-lib/src/git/repo.rs
git-branchless-lib/src/git/test.rs
git-branchless-lib/src/testing.rs
git-branchless-submit/Cargo.toml
git-branchless-submit/src/branch_forge.rs
git-branchless-submit/src/github.rs
git-branchless-submit/src/lib.rs
git-branchless-submit/tests/test_github_forge.rs

**Stack:**
---
feat(submit:github): implement Github forge
- It's not very good. It's probably buggy since there's a huge amount of state to keep in sync between commits, branches, and pull requests.
- It's not very useful. When using Github's "Rebase and merge" button, it always rewrites the commit to update the committer signature. Then, for some reason, descendant commits can't be rebased automatically, and you have to manually rebase them.

[1/1] feat(submit:github): implement Github forge

---

git-branchless-lib/src/git/run.rs

Closes #1256, closes #370, closes #1144

fix(hooks): different PATH's name on windows and linux

---

git-branchless-test/src/lib.rs

cleanup: fix lint for Rust 1.77

cleanup: fix lint for Rust 1.77

---

.gitignore

For us Nix(OS) developers, useful with: `echo 'use flake' > .envrc` to automatically load the development shell for this project.

chore: ignore direnv files

---

.github/workflows/linux-git-devel.yml
.github/workflows/linux.yml
.github/workflows/macos.yml
.github/workflows/windows.yml
.gitpod.yml
Cargo.lock
git-branchless/Cargo.toml

**Stack:**
* https://github.com/arxanas/git-branchless/pull/1292
* https://github.com/arxanas/git-branchless/pull/1293
---
build: update MSRV to 1.74
It may become difficult to upgrade dependencies in the future.
- I don't want to fall too far behind. Many automatic dependency updates are now failing, indicating that breaking changes are happening upstream that we haven't integrated.
- Since git-branchless is a CLI application, it doesn't have its downstream dependents to worry about breaking.
The specific value is somewhat arbitrary:
- We're just following `clap`'s current MSRV,
- which aims to trail the latest Rust version by 6-9 months
- (and the management of `clap`'s MSRV is its entire own topic).
- My hope is that many applications in the Rust ecosystem also follow the `clap` MSRV …

[2/2] build: update MSRV to 1.74

---

git-branchless-hook/src/lib.rs
git-branchless-lib/src/git/repo.rs
git-branchless/tests/test_hooks.rs

In git 2.45, reference transactions now support symbolic refs (see:
https://github.com/git/git/commit/a8ae923f85da6434c3faf9c39719d6d5e5c77e65)
To support this, we add a transaction reference resolver that's capable of
looking up the Oid for a named reference. It requires a repository object to
do this successfully.
To support the functionality, a new `refname_to_id` function is added to the
Repo object that calls the similarly named method on the inner repository to
get the `git2::Oid` for a given reference name.

Fix for Bug #1321 - Support symbolic refs in tx lines for git 2.45

---

git-branchless-opts/src/lib.rs
git-branchless-submit/src/lib.rs
git-branchless-submit/src/phabricator.rs

**Stack:**
* https://github.com/arxanas/git-branchless/pull/1353
* https://github.com/arxanas/git-branchless/pull/1354
* https://github.com/arxanas/git-branchless/pull/1355
* https://github.com/arxanas/git-branchless/pull/1356
* https://github.com/arxanas/git-branchless/pull/1202
* https://github.com/arxanas/git-branchless/pull/1357
* https://github.com/arxanas/git-branchless/pull/1358
---
docs(submit): Adjust some messaging to be more forge-agnostic

[2/7] docs(submit): Adjust some messaging to be more forge-agnostic

---

git-branchless-opts/src/lib.rs
git-branchless-submit/src/lib.rs

**Stack:**
* https://github.com/arxanas/git-branchless/pull/1353
* https://github.com/arxanas/git-branchless/pull/1354
* https://github.com/arxanas/git-branchless/pull/1355
* https://github.com/arxanas/git-branchless/pull/1356
* https://github.com/arxanas/git-branchless/pull/1202
* https://github.com/arxanas/git-branchless/pull/1357
* https://github.com/arxanas/git-branchless/pull/1358
---
feat(submit): support passing `--jobs`
This is currently used only by the Phabricator forge, which uses the `git test` infrastructure to run `arc` on several commits at once. I don't know how well it works when an error occurs.

[3/7] feat(submit): support passing `--jobs`

---

rust-toolchain.toml

build: add `rust-toolchain.toml`
It seems easier for contributors to get started if the compiler version is already configured; plus, this will presumably make it so that I don't have to set the Rust version with `rustup override` whenever I create a new worktree.

build: add `rust-toolchain.toml`

---

Cargo.lock
Cargo.toml

The problem has been fixed in recent libgit2 releases, as included in git2-rs 0.19.
Fix #1200 
Note: this needs to be merged after #1392 in order for the CI to be green

fix: allow deleting a branch when config entries contain multivars

---

git-branchless-lib/src/testing.rs

At least on macOS, the tests are failing if the system locale is not set to English. This change pins the git locale to `C` so they work independent of the system locale.
Example test failure (macOS 14.6.1, German system locale):
```
────────────┬───────────────────────────────────────────────────────────────────
0       │-HEAD detached from 96d1c37
1       │-Changes to be committed:
2       │-  (use "git restore --staged <file>..." to unstage)
3       │-  new file:   test3.txt
0 │+HEAD losgelöst von 96d1c37
1 │+Zum Commit vorgemerkte Änderungen:
2 │+  (benutzen Sie "git restore --staged <Datei>..." zum Entfernen aus der Staging-Area)
3 │+  neue Datei:     test3.txt
4     4 │
5       │-Changes to be committed:
5 │+Zum Commit vorgemerkte Änderungen:
6     6 │ diff --git c/test3.txt …
```

fix: make tests independent of system locale

---

Cargo.lock
Cargo.toml
git-branchless-invoke/src/lib.rs

Closes #1444.
This depends on libgit2 1.9.0 which is contained in git2 0.20.

build: bump git2 0.19 -> 0.20 to unlock ^ref spec

---

CHANGELOG.md
git-branchless-lib/src/git/repo.rs
git-branchless-navigation/src/lib.rs
git-branchless-opts/src/lib.rs
git-branchless/tests/test_navigation.rs

This updated `git switch` to accept a revset as it's argument, and also to support `-` (to checkout previously checked out branch/commit) by passing it through to git.
The revset parameter must evaluate to a set with a single head, and I've found this handy in cases like `current(...)` to move to the latest version of a commit if I had an old smartlog or SHA still on screen or such, and also `switch foo:` for when I have a branch ref handy but I really want to checkout the latest detached commit in that stack.
But with revset support added, `switch -` broke because it looked a poorly formed revset:
```
Message:  A fatal error occurred:
0: parse error in "-": parse error: Unrecognized token `-` found at 0:1
Expected one of "(", "..", ":", "::", a commit/branch/tag or a string literal
1: …
```

feat(switch): accept revset arguments, and explicitly support `-` shorthand

---

.github/workflows/release.yml

https://github.com/raylu/git-branchless/actions/runs/13598267205 built https://github.com/raylu/git-branchless/releases/tag/v0.10.0
closes #1517

ci: arm64 binaries

---

git-branchless-init/src/lib.rs
git-branchless-lib/src/core/check_out.rs
git-branchless-lib/src/git/diff.rs
git-branchless-lib/src/git/index.rs
git-branchless-lib/src/git/mod.rs
git-branchless-lib/src/git/status.rs
git-branchless-lib/src/git/tree.rs
git-branchless-lib/src/testing.rs
git-branchless-lib/tests/test_rewrite_plan.rs
git-branchless-navigation/src/lib.rs
git-branchless-opts/src/lib.rs
git-branchless-record/src/lib.rs
git-branchless-reword/src/lib.rs
git-branchless-undo/src/lib.rs
git-branchless/Cargo.toml
git-branchless/src/commands/amend.rs
git-branchless/src/commands/mod.rs
git-branchless/src/commands/restack.rs
git-branchless/src/commands/split.rs
git-branchless/src/commands/sync.rs
git-branchless/tests/test_init.rs
git-branchless/tests/test_split.rs

This adds a `git split` command to extract changes from commits. This mostly addresses #180, except for the `-i/--interactive` part. The split and rebase happens in-memory, so it should be fast. The command signature is
`git [branchless] split <revset> <file> [<file>...]`
- `<revset>` must resolve to a single commit (or just be a single commit, or `@`, etc)
- if only one file is given, then the file name is used in the extracted commit message
- if 2+ files are split out, then `<n> files` is used in the extracted commit message
- in either case, a brief insert/delete summary is also used, eg `(+2/-5)`
- eg `temp(split): lib.rs (+5)` or `temp(split): 3 files (+3/-3)`
These alter how the split/rebase happens:
- _default_ (no flags) is "insert after": extracted changes are inserted into …

feat: add `split` command

---

git-branchless-lib/src/core/rewrite/execute.rs
git-branchless-lib/tests/test_rewrite_plan.rs
git-branchless-move/src/lib.rs
git-branchless-opts/src/lib.rs
git-branchless-record/src/lib.rs
git-branchless-reword/src/lib.rs
git-branchless-submit/src/phabricator.rs
git-branchless-test/src/lib.rs
git-branchless/src/commands/amend.rs
git-branchless/src/commands/mod.rs
git-branchless/src/commands/restack.rs
git-branchless/src/commands/split.rs
git-branchless/src/commands/sync.rs
git-branchless/tests/test_move.rs

I have found this useful to find the exact commit that introduced a conflict for an out of date stack:
```
TEST_COMMAND='
git move \
-s "current($OLD_COMMIT)" \
-d $BRANCHLESS_TEST_COMMIT \
--in-memory \
--dry-run
'
git test run \
"current($OLD_COMMIT)..main" \
--exec "$TEST_COMMAND"
--jobs 8 \
--strategy worktree
--search binary
```
This example was able to search through 372 commits in only 40 iterations, finding the exact commit where the conflict was created. This made the resolution a lot easier vs just rebasing directly onto main and having to deal with potentially numerous, combined conflicts.

feat(move): add --dry-run to support testing in-memory rebases
