arxanas/git-branchless

README.md
I'm glad you found my project and mentioned it in the wiki and on Hacker News :) Thanks! Also, I really like the interactive undo feature. I've wanted to add that kind of "time travel" feature to jj too.
This PR adds a mention of it to the READMe's list of alternative tools. Let me know what you think. I'd understand if you think it should not be listed either because it's still experimental, or because it's too different by not being able to run in an existing git working copy.
=> readme: add a mention of my experimental VCS "Jujutsu"

src/commands/wrap.rs, src/testing.rs, tests/command/test_smartlog.rs
=> Fix hardcoded paths for NixOS packaging

CHANGELOG.md, src/commands/init.rs, src/testing.rs, src/util.rs, tests/command/test_init.rs, tests/command/test_smartlog.rs, tests/command/test_undo.rs, tests/mod.rs, tests/util.rs
- tests(init): make basic snapshot test
- init: auto-detect main branch name, if possible
- init: improve error message when main branch not found
=> Improve main branch UX (fixes #14)

CHANGELOG.md, src/commands/init.rs, src/main.rs, tests/command/test_init.rs
- refactor(init): factor out hooks/aliases
- init: add --uninstall option
Closes #15.
=> Add `git branchless init --uninstall`

CHANGELOG.md, src/core/rewrite.rs, src/util.rs, tests/command/test_move.rs, tests/command/test_restack.rs
- fix(util): stream output from Git subcommands
- feat(move): fix spacing in progress message about calling Git
=> Stream Git output

CHANGELOG.md, src/commands/gc.rs, src/commands/hide.rs, src/commands/hooks.rs, src/commands/move.rs, src/commands/navigation.rs, src/commands/restack.rs, src/commands/smartlog.rs, src/commands/undo.rs, src/commands/wrap.rs, src/core/config.rs, src/core/eventlog.rs, src/core/metadata.rs, src/core/rewrite.rs, src/git/repo.rs, src/git/run.rs, tests/command/test_init.rs, tests/command/test_move.rs, tests/command/test_restack.rs, tests/command/test_smartlog.rs, tests/command/test_undo.rs, tests/command/test_wrap.rs, tests/core/test_eventlog.rs, tests/core/test_hooks.rs
- feat(rewrite): print updated names in `reference-transaction`
- fix(rewrite): treat branch names more carefully
=> Improve branch name discipline

CHANGELOG.md, src/commands/hide.rs, src/commands/hooks.rs, src/commands/navigation.rs, src/commands/undo.rs, src/core/rewrite.rs, src/git/repo.rs, src/git/run.rs, src/testing.rs, tests/command/test_move.rs, tests/command/test_restack.rs, tests/core/test_hooks.rs
- refactor(repo): add helper functions to friendly describe commits
- feat(rewrite): use constraint-solving approach to build rebase plans
- feat(hooks): display affected objects in some hook messages
=> Improve hook messages

.github/workflows/lint.yml
This reverts commit 3266bcca162519d16d8a731e6bef64a708cdcf09.
=> Revert "ci: use `actions-rs/clippy-check` action"

.github/workflows/lint.yml, .github/workflows/linux-git-devel.yml, .github/workflows/linux.yml, .github/workflows/macos.yml, .github/workflows/windows.yml, Cargo.toml
See https://matklad.github.io/2021/09/04/fast-rust-builds.html.
=> build: some CI improvements

src/core/graph.rs, tests/command/test_smartlog.rs
=> fix(smartlog): don't show active public commits unnecessarily

CHANGELOG.md, src/commands/gc.rs, src/core/config.rs, src/git/run.rs, tests/command/test_move.rs
=> Reduce incidence of garbage collection references

.github/workflows/nix-macos.yml
cc @hmenke re https://github.com/arxanas/git-branchless/pull/159#issuecomment-958611320
=> ci: disable Nix on macOS job

src/commands/init.rs
=> init: fix `post-merge` hook formatting

.github/workflows/nix-linux.yml, .github/workflows/nix-macos.yml
This reverts commit e2decb80364922056e29e6d1b1006bd4ca6681ab.
=> ci: use GITHUB_TOKEN in Nix build

CHANGELOG.md, src/core/rewrite/evolve.rs, tests/command/test_restack.rs
=> fix(restack): don't resurrect commits not observed by the event log

src/git/repo.rs, src/testing.rs
cc @bcongdon for future reference
=> fix(testing): don't use inherited environment for `test_get_status`

src/testing.rs
=> fix(testing): show suggestion when `PATH_TO_GIT` is not set

CHANGELOG.md, src/commands/init.rs, tests/command/test_init.rs
=> feat(init): warn if `core.hooksPath` is set

CHANGELOG.md, src/commands/restack.rs, tests/command/test_amend.rs, tests/command/test_move.rs, tests/command/test_restack.rs
=> fix(restack): don't erroneously check out old commit

Cargo.lock, Cargo.toml, src/core/formatting.rs
Based on some feedback, I shortened the name.
=> chore: Upgrade concolor

.github/workflows/linux-git-devel.yml, .github/workflows/linux.yml, .github/workflows/macos.yml, .github/workflows/windows.yml, .gitpod/Dockerfile, flake.nix, src/commands/mod.rs, src/core/config.rs, src/testing.rs
=> Update test environment variables

flake.nix
This makes it easier for Nix users to use a different version of Rust to compile git-branchless, e.g.
```nix
pkgs.git-branchless.override {
rustPlatform = pkgs.rustPackages_1_57.rustPlatform;
}
```
The motivation behind this PR is that the stable NixOS 21.11 is still on Rust 1.56 by default for `rustPlatform` and https://github.com/arxanas/git-branchless/commit/a7ea5ccff54e3a01db8393413c6f5cd49c9a22c6#diff-af29e66a62cac9974dc3f8f7132badf0438c5c4d3426a03492425cf56c691b15R256 introduced `Command::get_envs()` which needs the library feature `command_access` which is only available in Rust 1.57.
=> ci: make Nix derivation more overridable

.github/workflows/linux-git-devel.yml, .github/workflows/linux.yml, .github/workflows/macos.yml, .github/workflows/windows.yml, Cargo.toml, src/testing.rs
Regarding https://github.com/arxanas/git-branchless/pull/276.
=> ci: set Rust v1.56.0 as minimum supported version

Cargo.lock, Cargo.toml, src/commands/bug_report.rs, src/commands/mod.rs, src/commands/navigation.rs, src/commands/smartlog.rs, src/commands/undo.rs, src/core/node_descriptors.rs, src/git/repo.rs, src/opts.rs, tests/command/test_bug_report.rs, tests/mod.rs
=> Create `git branchless bug-report` command

CHANGELOG.md, src/commands/mod.rs, src/commands/undo.rs, src/opts.rs, tests/command/test_undo.rs
=> feat(undo): undo most recent operation by default

CHANGELOG.md, src/commands/restack.rs, src/core/rewrite/evolve.rs, src/core/rewrite/rewrite_hooks.rs, src/testing.rs, tests/command/test_restack.rs
=> fix(restack): restack non-observed visible descendant commits

src/commands/reword.rs, src/core/config.rs
This is my attempt to address #328.
There are no tests for the code path that involves the editor, but I was able to test this myself manually via:
```
$ cargo run -- reword                   # used `vi`
$ GIT_EDITOR=nano cargo run -- reword   # used `nano`
$ git config core.editor nano
$ cargo run -- reword                   # used `nano`
$ git config --unset core.editor
$ cargo run -- reword                   # used `vi`
```
=> feat(reword): use `$GIT_EDITOR` and `core.editor`, if configured (close #328)

CHANGELOG.md, git-branchless-lib/src/core/rewrite/execute.rs, git-branchless-lib/src/core/rewrite/mod.rs, git-branchless/src/commands/amend.rs, git-branchless/src/commands/mod.rs, git-branchless/src/commands/move.rs, git-branchless/src/commands/restack.rs, git-branchless/tests/command/test_amend.rs
=> fix(amend): suggest `git restack -m` instead of `git amend -m`

.github/workflows/lint.yml, .github/workflows/linux-git-devel.yml, .github/workflows/linux.yml, .github/workflows/macos.yml, .github/workflows/windows.yml, git-branchless/src/commands/undo.rs
=> ci: set `override: true` for `rustup`

git-branchless-lib/src/core/config.rs, git-branchless-lib/src/git/repo.rs, git-branchless/src/commands/reword.rs
=> fix(reword): attempt to read editor from `git var` first

git-branchless/src/commands/reword.rs
From https://github.com/arxanas/git-branchless/issues/371#issuecomment-1121540003:
> That being said, @claytonrcarter, maybe it would make sense to remove the header if only one commit is being reworded? In addition to the user surprise here, I also personally have the problem that I want to immediately start typing on the focused line, but then I accidentally overwrite the reword header.
Thanks for the nudge. It had been bugging me, too! I believe that this change handles this case, though I haven't hammered on it. It's passed the "fiddle around with it" test for the past hour, though. 😄 
cc @AaronLieberman
=> feat(reword): Omit marker line when editting exactly 1 commit

CHANGELOG.md, git-branchless-lib/src/core/effects.rs, git-branchless/src/commands/mod.rs, git-branchless/src/commands/repair.rs, git-branchless/src/commands/smartlog.rs, git-branchless/src/opts.rs, git-branchless/tests/command/test_init.rs, git-branchless/tests/command/test_repair.rs, git-branchless/tests/mod.rs
=> Create `git branchless repair` command

git-branchless-lib/src/core/eventlog.rs, git-branchless/src/commands/bug_report.rs, git-branchless/src/commands/init.rs, git-branchless/tests/command/test_bug_report.rs
=> Add more information to `git branchless bug-report`

git-branchless-lib/src/git/snapshot.rs, git-branchless-lib/src/git/status.rs, git-branchless/tests/command/test_amend.rs, git-branchless/tests/command/test_snapshot.rs
=> Fix undoing `git amend` with detached HEAD

git-branchless/src/commands/reword.rs
Oops, sorry I didn't catch #434 back when I was working on #366. This should take care of it.
=> fix(reword): Correct message about multiple commits (close #434)

git-branchless/src/commands/move.rs, git-branchless/src/opts.rs, git-branchless/src/revset/eval.rs, git-branchless/tests/command/test_move.rs, git-branchless/tests/command/test_query.rs
=> Support revsets in `git move`

git-branchless/src/commands/move.rs, git-branchless/tests/command/test_move.rs
#450 included a restriction that each component or range of commits being moved had to have a single HEAD. This restriction was from an earlier implementation of `move --exact` that didn't use connected components, and -- as far as I can tell -- isn't actually needed. See comment https://github.com/arxanas/git-branchless/pull/450#issuecomment-1188497505 for an example.
@arxanas can you take a peek at [this test fixture that I updated](https://github.com/arxanas/git-branchless/pull/466/files#diff-40097149f604160704079190c192ae81be5fbfc762b3d6e6e703be79e82a2e07L2032-L2043). It's hard to follow in the diff, but basically it looks like it changed from `test3 <-- test6` to `test2 <-- test6` ... which I *think* is actually correct. (Everything else appears to have stayed the same.) Can you take …
=> feat(move --exact): Remove single HEAD restriction

git-branchless-lib/benches/benches.rs, git-branchless-lib/src/core/rewrite/mod.rs, git-branchless-lib/src/core/rewrite/plan.rs, git-branchless/src/commands/move.rs, git-branchless/src/commands/restack.rs, git-branchless/src/commands/reword.rs, git-branchless/src/commands/sync.rs, git-branchless/tests/command/test_reword.rs
=> Improve reword experience on public commits

git-branchless-lib/src/core/dag.rs, git-branchless-lib/src/core/rewrite/plan.rs, git-branchless/src/commands/move.rs, git-branchless/src/commands/query.rs, git-branchless/src/commands/restack.rs, git-branchless/src/commands/smartlog.rs, git-branchless/src/commands/submit.rs, git-branchless/src/revset/eval.rs, git-branchless/tests/command/test_query.rs
=> Print query output in correct order

git-branchless/src/commands/undo.rs, git-branchless/tests/command/test_undo.rs
=> Fix crash in `git undo -i`

Cargo.lock, git-branchless-lib/src/core/config.rs, git-branchless-lib/src/core/effects.rs, git-branchless-lib/src/core/rewrite/execute.rs, git-branchless-lib/src/core/rewrite/mod.rs, git-branchless-lib/src/core/rewrite/plan.rs, git-branchless-lib/src/git/repo.rs, git-branchless-lib/src/git/run.rs, git-branchless-lib/src/git/status.rs, git-branchless-lib/src/git/tree.rs, git-branchless-lib/src/testing.rs, git-branchless/Cargo.toml, git-branchless/src/commands/init.rs, git-branchless/src/commands/mod.rs, git-branchless/src/commands/reword.rs, git-branchless/src/commands/snapshot.rs, git-branchless/src/commands/test.rs, git-branchless/src/opts.rs, git-branchless/src/revset/eval.rs, git-branchless/tests/command/test_amend.rs, git-branchless/tests/command/test_move.rs, git-branchless/tests/command/test_navigation.rs, git-branchless/tests/command/test_record.rs, git-branchless/tests/command/test_restack.rs, git-branchless/tests/command/test_snapshot.rs, git-branchless/tests/command/test_submit.rs, git-branchless/tests/command/test_test.rs, git-branchless/tests/mod.rs
Like this one: https://github.com/spotify/git-test
Ideally, we'll be able to use this command to be able to run a linter/formatter and apply changes to an entire stack of commits.
=> Create `git test` command

git-branchless-lib/src/core/dag.rs, git-branchless/src/commands/move.rs, git-branchless/src/commands/smartlog.rs
This removes some dag functions and replaces them dag operations, as mentioned at  https://github.com/arxanas/git-branchless/pull/619/files/08134fa4127c808ef1457b1a36a418ab258b8c10#r1014902301
=> refactor(dag): Remove legacy functions

git-branchless-lib/src/core/dag.rs, git-branchless/src/revset/builtins.rs, git-branchless/src/revset/eval.rs, git-branchless/src/revset/resolve.rs, git-branchless/tests/command/test_smartlog.rs
=> Fix showing hidden commits in smartlog

git-branchless/src/commands/init.rs, git-branchless/tests/command/test_init.rs
This ports 6db6532f178b50d765cb92d0360025950e4bfc17 to the uninstall hooks too.
=> feat(init): collapse uninstalled hook output to one line

git-branchless-lib/src/core/eventlog.rs, git-branchless/src/commands/init.rs, git-branchless/tests/command/test_init.rs
Updated version of https://github.com/arxanas/git-branchless/pull/667. Closes #308.
=> feat(init): populate DAG during initialization

git-branchless/src/commands/submit.rs
This is a small patch to `git submit` to style the pushed/skipped branches with colors. My goal is to improve on the default output, which doesn't make it very easy to quickly identify the pushed/skipped branches w/o reading the output carefully. 
- This was mostly lifted from `git test` and how it styles passing/skipped/failed tests.
=> feat(submit): Apply styles to branch names

git-branchless/src/commands/amend.rs, git-branchless/tests/test_amend.rs
=> fix(amend): don't detach current branch when amending

git-branchless-lib/src/core/config.rs, git-branchless-lib/src/git/run.rs, git-branchless/src/commands/bug_report.rs, git-branchless/src/commands/init.rs, git-branchless/src/commands/mod.rs, git-branchless/tests/test_init.rs
=> fix(init): warn when using dynamically-calculated hooks path

Cargo.lock, git-branchless-reword/Cargo.toml, git-branchless-reword/src/dialoguer_edit.rs, git-branchless-reword/src/lib.rs
=> fix(reword): support invoking editors with spaces in name

git-branchless-lib/src/core/config.rs, git-branchless-opts/src/lib.rs, git-branchless-revset/src/resolve.rs, git-branchless-smartlog/src/lib.rs, git-branchless-smartlog/tests/test_smartlog.rs, git-branchless/src/commands/restack.rs, git-branchless/tests/test_init.rs
cc @claytonrcarter, since I think you had mentioned wanting/working on such a feature; not sure where that discussion went.
Closes #839.
=> smartlog: add default revset config option

Cargo.lock, git-branchless-lib/Cargo.toml, git-branchless-lib/bin/testing/regression_test_record.rs, git-branchless-lib/src/git/diff.rs, git-branchless-record/Cargo.toml, git-branchless-record/src/lib.rs, git-branchless-record/tests/test_record.rs, scm-record/Cargo.toml, scm-record/examples/static_contents.rs, scm-record/src/render.rs, scm-record/src/types.rs, scm-record/src/ui.rs, scm-record/tests/test_scm_record.rs
=> Switch to `scm-record` library

git-branchless-lib/src/git/run.rs
This works around https://github.com/libgit2/libgit2/issues/6401 by using the current working directory, instead of `libgit2`'s incorrect repo working copy path, when a `repo` project is detected.
=> fix(git): fix "not a git repository" when running in `repo` projects

git-branchless-lib/tests/test_git_run.rs
I forgot to add a test in #900, oops!
This test is Windows only, as creating symlinks on Windows requires administrator / developer privileges.
=> tests(git): add test for running commands in `repo` tool projects

git-branchless-lib/src/git/run.rs
This handles `repo`-managed working copies, and should be generic enough to handle most other cases (unless the symlink points to a child of an ancestor).
=> fix(git): simplify and generalise "symlinked `.git` directory" check

git-branchless/src/commands/sync.rs, git-branchless/tests/test_sync.rs
=> fix(sync): don't leave dirty index when running `git sync --pull` with `main` checked out

git-branchless-lib/bin/testing/regression_test_record.rs, git-branchless-lib/src/git/diff.rs, git-branchless-record/tests/test_record.rs, git-branchless-testing/src/lib.rs, git-record/README.md, scm-record/README.md, scm-record/benches/benches.rs, scm-record/examples/static_contents.rs, scm-record/src/bin/scm-diff-editor.rs, scm-record/src/render.rs, scm-record/src/types.rs, scm-record/src/ui.rs, scm-record/tests/example_contents.json, scm-record/tests/test_scm_record.rs, scm-record/tests/ui_state.1.json
Sticky header demo:
https://user-images.githubusercontent.com/454057/236634332-7f8e3853-e7e6-4cb8-894d-7fca52bc66a1.mov
=> scm-record features

scm-record/README.md, scm-record/src/render.rs, scm-record/src/ui.rs, scm-record/tests/test_scm_record.rs
=> feat(record): add menu bar

flake.nix
This makes it trivial to install `scm-diff-editor` using `nix-env` or `nix profile install`, e.g.
nix profile install github:arxanas/git-branchless#scm-diff-editor
=> feat(nix): add 'scm-diff-editor' package

scm-record/src/scm_diff_editor.rs, scm-record/src/types.rs, scm-record/tests/test_scm_record.rs
=> fix(record): don't add new files with no selected contents

Cargo.lock, scm-record/Cargo.toml, scm-record/src/render.rs, scm-record/src/ui.rs
=> scm-record: upgrade from unmaintained `tui` crate to `ratatui`

README.md
Several of the suggestions are already pretty good,
so I wanted to rephrase it so that people gave them
a look too, without preventing newer, even awesomer
suggestions, of course.
=> Change 'suggest' to 'discuss'

scm-bisect/src/search.rs
**Stack:**
* https://github.com/arxanas/git-branchless/pull/1175
* https://github.com/arxanas/git-branchless/pull/1176
* https://github.com/arxanas/git-branchless/pull/1177
* https://github.com/arxanas/git-branchless/pull/1162
---
docs(bisect): update some comments on bounds
=> [1/4] docs(bisect): update some comments on bounds

git-branchless-test/src/lib.rs, scm-bisect/src/search.rs
**Stack:**
* https://github.com/arxanas/git-branchless/pull/1176
* https://github.com/arxanas/git-branchless/pull/1177
* https://github.com/arxanas/git-branchless/pull/1162
---
refactor(bisect): make `Strategy` into trait
We will want to add more kinds of strategies in the future (in particular, minimization involves a strategy operating on the power set of nodes).
=> [1/3] refactor(bisect): make `Strategy` into trait

git-branchless-lib/src/core/effects.rs, git-branchless-lib/src/core/rewrite/plan.rs, git-branchless-submit/src/phabricator.rs, git-branchless/src/commands/repair.rs, git-branchless/src/commands/sync.rs
**Stack:**
* https://github.com/arxanas/git-branchless/pull/1234
---
feat(effects): add `with_progress` method to iterators
In situations where we `continue` a loop, the naive approach of incrementing the iterator progress at the end of the loop won't work as it'll skip the increment. This extension method aims to improve the ergonomics and correctness of that use-case.
=> [1/1] feat(effects): add `with_progress` method to iterators

scm-bisect/src/basic.rs, scm-bisect/src/lib.rs, scm-bisect/src/testing.rs
**Stack:**
* https://github.com/arxanas/git-branchless/pull/1233
---
testing(bisect): extract symbols into `testing` module
=> [1/2] testing(bisect): extract symbols into `testing` module

.github/workflows/linux-git-devel.yml, .github/workflows/linux.yml, .github/workflows/macos.yml, .github/workflows/windows.yml, .gitpod.yml, Cargo.lock, git-branchless-submit/src/lib.rs, git-branchless/Cargo.toml
**Stack:**
* https://github.com/arxanas/git-branchless/pull/1292
* https://github.com/arxanas/git-branchless/pull/1293
---
feat(submit:github): disable Github forge detection by default
Prerequisite for a new release so that we don't break everyone who is submitting to Github.
=> [1/2] feat(submit:github): disable Github forge detection by default

git-branchless-lib/src/git/repo.rs
Fixes: https://github.com/arxanas/git-branchless/issues/1404
=> Skip headers in status output
